name: flower_detection_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hexcolor: ^3.0.1
  image_picker: ^0.8.9
  tflite_flutter: ^0.10.4
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  flutter_tflite: ^1.0.1
  # image_picker: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:

  uses-material-design: true

  assets:
     - images/
     - assets/

  fonts:
     - family: ArchivoBlack
       fonts:
         - asset: fonts/ArchivoBlack-Regular.ttf


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700